<?php

use App\Core\Config;
use App\Model\Account\User;
use App\Model\ServiceRequest;


//for edit mode
$requestModel = $this->var('requestModel', null);

//$readonly = $this->var('readonly', false);
$readonly = ($requestModel?->isCompleted() && !User::isAdmin()) ;

$additionalData = $requestModel?->getAdditionalData() ?? [];
$attachments = $requestModel?->getAttachments();

//Kind of service request (request or self track)
$serviceKind = $requestModel?->get('kind') ?? $this->var('kind', ServiceRequest::KIND_REQUEST);
$isSelfTracking = $serviceKind === ServiceRequest::KIND_SELF_TRACKING;

//Collections
$parcelCollection = $this->var('parcelCollection', []);
$blockCollection = $this->var('blockCollection', null);

// Parcel Model if requested for
$parcelModel = $requestModel?->getParcel() ?? $this->var('parcelModel', null);


//Javascript for form (depends on php variables)
include __DIR__ . '/form_components/form.js.phtml';

if (User::isAdmin()) { //Complete dialog for admin
  include_once __DIR__ . '/dialog/complete.phtml';
}

if (User::isAdmin() || $isSelfTracking) { //attachments are only for admin or self tracking
  include __DIR__ . '/dialog/attachment.phtml';
}
?>

<div class="entity-form card">
  <form method="post" id="service-form">
    <input type="hidden" name="service[kind]" value="<?= htmlspecialchars($serviceKind) ?>">
    <?php if ($requestModel?->getId()): ?>
      <input type="hidden" name="service[id]" value="<?= (int)$requestModel?->getId() ?>">
      <input type="hidden" name="service[status]" value="<?= $requestModel?->getStatus() ?? ServiceRequest::STATUS_PENDING ?>">
      <input type="hidden" name="service[account_id]" value="<?= (int)$requestModel?->getAccountId() ?>">
    <?php endif ?>

    <div style="display:flex; justify-content: space-between; margin-bottom: 1rem; align-items: center;">
      <?php if ($requestModel?->getId()): ?>
        <h2>Update</h2>
          <span class="kind kind-<?php echo $requestModel?->get('kind') ?>"><?php echo ucfirst(str_replace('_', ' ', $requestModel?->get('kind'))) ?></span>
          <?php if (User::isAdmin() && $requestModel?->isCompleted()): ?>
            <a class="status status-<?= htmlspecialchars($requestModel?->getStatus()) ?>" href="/service/complete_details?id=<?= $requestModel->get('id') ?>">Complete Details</a>
          <?php else: ?>
            <span class="status status-<?= htmlspecialchars($requestModel?->getStatus()) ?>">
              <?php echo ucfirst($requestModel?->getStatus()) ?>
            </span>
            <?php endif;?>
      <?php else: ?>
        <?php if ($isSelfTracking): ?>
          <h2>Self Tracking</h2>
        <?php else: ?>
        <h2>Request a Service</h2>
        <?php endif; ?>
      <?php endif; ?>
    </div>
    <div class="fld-row" style="display: flex; gap: 5px;">
      <div class="fld" style="flex: 1;">
        <?php if ($parcelModel?->getId()): ?>
          <input type="text" disabled value="<?= htmlspecialchars($parcelModel->getName()) ?>">
          <input type="hidden" name="service[parcel_id]" value="<?= (int)$parcelModel->getId() ?>">
        <?php else: ?>
          <select name="service[parcel_id]" required>
            <?php if ($parcelCollection?->isEmpty()): ?>
            <?php endif ?>
            <option value="" hidden></option>
            <?php foreach ($parcelCollection as $parcelModel):?>
              <?php if (!$parcelModel->canRequestService()):?>
              <option value="<?= $parcelModel->getId() ?>" disabled><?= htmlspecialchars($parcelModel->getName()) ?>(Check Parcel)</option>
              <?php 
                continue; // Skip parcels that cannot be requested
                endif; 
              ?>
              <option value="<?= $parcelModel->getId() ?>"><?= htmlspecialchars($parcelModel->getName()) ?></option>
            <?php endforeach ?>
          </select>
        <?php endif ?>
        <label>Parcel</label>

      </div>
      <div class="fld" style="flex: 1;">
        <?php if ($requestModel?->getId()): ?>
          <input type="text" disabled value="<?= htmlspecialchars($requestModel?->getBlock()->get('name')) ?>">
          <input type="hidden" name="service[block_id]" value="<?= (int)$requestModel?->get('block_id') ?>">
        <?php elseif ($blockModel): ?>
          <input type="text" disabled value="<?= htmlspecialchars($blockModel->getName()) ?>">
          <input type="hidden" name="service[block_id]" value="<?= (int)$blockModel->getId() ?>">
        <?php else: ?>
          <select name="service[block_id]" required <?php if ($currentBlockId): ?>disabled<?php endif ?>>
            <?php if ($blockCollection?->isEmpty()): ?>
              <option value="" hidden></option>
              <?php foreach ($blockCollection as $block): ?>
                <option value="<?= $block->getId() ?>" <?php if ($block->getId() == $currentBlockId): ?>selected<?php endif ?>><?= htmlspecialchars($block->getName()) ?></option>
              <?php endforeach ?>
            <?php elseif ($parcelModel?->getId()): ?>
              <option value="" hidden></option>
              <?php foreach ($parcelModel->getBlocks() as $block): ?>
                <option value="<?= $block->getId() ?>" <?php if ($block->getId() == $currentBlockId): ?>selected<?php endif ?>><?= htmlspecialchars($block->getName()) ?></option>
              <?php endforeach ?>
            <?php else: ?>
              <option value="" disabled>Select Parcel first</option>
            <?php endif ?>
          </select>
        <?php endif ?>
        <label>Block</label>
      </div>
    </div>

    <?php include __DIR__ . '/form_components/fields/date.phtml'; ?>

    <div class="fld">
      <select name="service[type]" placeholder=" " required>
        <option value="" hidden></option>
        <?php
        foreach (Config::get('service_type') as $type): ?>
          <option
            value="<?= htmlspecialchars($type) ?>"
            <?php if ($requestModel?->get('type') == $type): ?>selected<?php endif ?>>
            <?= htmlspecialchars($type) ?>
          </option>
        <?php endforeach ?>
      </select>
      <label>Type</label>
    </div>

    <div class="fld">
      <textarea name="service[reason]" placeholder=" " rows="4"><?php echo $requestModel?->get('reason') ?: '' ?></textarea>
      <label>Reason & Notes</label>
    </div>

    <?php include __DIR__ . '/form_components/fields/custom_products.phtml'; ?>
    

    <fieldset id="application_usage" class="" data-allowed-types='<?= json_encode(Config::get('service_type_application')) ?>' style="display: none;">
      <legend>Application rate</legend>
      <div class="fld-row" style="justify-content: start;">
        <div class="fld">
          <select name="service[adds][application][unit]" style="width: auto;">
            <?php foreach (Config::get('units') as $unit): ?>
              <option
                value="<?= htmlspecialchars($unit) ?>"
                <?php if (isset($additionalData['application']['unit']) && $additionalData['application']['unit'] == $unit): ?>selected<?php endif ?>>
                <?= htmlspecialchars($unit) ?>
              </option>
            <?php endforeach ?>
          </select>
          <label>Unit</label>

        </div>
        <div class="fld">
          <input
            type="number"
            min="0"
            step="0.01"
            name="service[adds][application][volume]"
            placeholder=""
            value="<?= htmlspecialchars($additionalData['application']['volume'] ?? '') ?>">
          <label>Volume per acre</label>
        </div>
      </div>
    </fieldset>

    <?php include __DIR__ . '/form_components/attachments.phtml'; ?>

    <div class="button-set ">
      <!--button class="btn cancel" type="button" onclick="window.history.back()">Back</button-->
      <?php if (!$readonly): ?>
        <?php if ((User::isAdmin() || $isSelfTracking) && $requestModel?->getId()): ?>
          <button class="btn" type="button" onclick="document.getElementById('attachment-modal').classList.add('show')">Add attachment</button>
      <?php endif; ?>
        <?php if (User::isAdmin() && $requestModel?->isPending() && !$isSelfTracking): ?>
          <a href="javascript:void(0)" class="btn brand-red" type="button" onclick="cancelRequest(<?= $requestModel?->getId() ?>)">Cancel Service</a>
          <a href="javascript:void(0)" class="btn brand-yellow" type="button" onclick="completeDialog(<?= $requestModel?->getId() ?>)">Complete</a>
        <?php endif; ?>
        <?php if (User::isAdmin() && $requestModel?->isCompleted()): ?>
          <a href="javascript:void(0)" class="btn brand-yellow" type="button" onclick="confirmAction('Are you sure you want to UNCOMPLETE this service request?', function() {
            window.location.href = '/service/uncomplete?id=<?= $requestModel?->getId() ?>';
          })">Uncomplete</a>
        <?php endif; ?>
        <?php if (User::isAdmin() && $requestModel?->isCancelled()): ?>
          <a href="javascript:void(0)" class="btn" type="button" onclick="uncancelRequest(<?= $requestModel?->getId() ?>)">Restore</a>
        <?php endif; ?>
        <button class="btn brand-green" type="submit">
          <?php if ($requestModel?->getId()): ?>
            Update
          <?php else: ?>
            Create
          <?php endif; ?>
        </button>
      <?php endif; ?>
    </div>
  </form>
</div>