<?php

use App\Core\Config;

$blockModel = $this->var('blockModel');
$block = $blockModel?->getData() ?? [];
$parcels = $this->var('parcels', []);
?>
<div class="card entity-form">
  <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:1rem">
    <h2>
      Block info
    </h2>
    <?php if ($blockModel?->getParcel()?->getId()): ?>
      <div class="button-top-set">
        <a class="btn brand-yellow" href="/?q=service/request&parcel=<?= $blockModel?->getParcel()?->getId() ?>&block=<?= $block['id'] ?>">Request Service</a>
      </div>
    <?php endif ?>
  </div>

  <form method="post" id="block-form">
    <input type="hidden" name="block[id]" value="<?= $block['id'] ?>">
    <div class="fld">
      <?php if ($block['id']): ?>
        <input type="text" disabled value="<?= $blockModel->getParcel()->get('name') ?>">
      <?php else: ?>
        <select name="block[parcel_id]" required>
          <option value="" hidden></option>
          <?php foreach ($parcels as $p): ?>
            <option value="<?= $p['id'] ?>" <?= $p['id'] === $block['parcel_id'] ? 'selected' : '' ?>><?= htmlspecialchars($p['name']) ?></option>
          <?php endforeach ?>
        </select>
      <?php endif ?>
      <label>Parcel</label>

    </div>
    <div class="fld">
      <input name="block[name]" placeholder=" " required value="<?= htmlspecialchars($block['name']) ?>">
      <label>Identifier</label>
    </div>

    <div class="fld">
      <select name="block[crop_category]" required>
        <option value="" hidden></option>
        <?php foreach (Config::get('crop_category') as $cat): ?>
          <option value="<?= $cat ?>" <?= $cat === $block['crop_category'] ? 'selected' : '' ?>><?= htmlspecialchars($cat) ?></option>
        <?php endforeach ?>
      </select>
      <label>Usage Type</label>
    </div>

    <!--div class="fld">
      <input type="number" step="0.01" name="block[acres]" placeholder=" " required value="<?= htmlspecialchars($block['acres']) ?>">
      <label>Acres</label>
    </div-->
    <div class="fld">
      <textarea name="block[notes]" placeholder=" " rows="2"><?= htmlspecialchars($block['notes']) ?></textarea>
      <label>Notes</label>
    </div>


    <div class=button-set>
      <div>
          <button class="btn cancel" type="button" onclick="window.history.back()">Back</button>
      </div>
      <div style="display:flex;gap:1rem">
        <form class="" method="post" action="/?q=block/deleteit">
          <input type="hidden" name="block[dp]" value="<?= $block['id'] ?>">
        </form>
        <button class="btn end brand-green" type="submit">
          <?php if ($block['id']): ?>
            Save
          <?php else: ?>
            Create
          <?php endif ?>
        </button>
      </div>
    </div>
  </form>
</div>