<?php 
$accounts = $this->var('accounts');
?>
<style>
    
</style>
<div id="account-list" class="entity-form">
    <div class="card">
        <table class="grid">
            <thead>
                <tr>
                    <th>Username</th>
                    <th>Full Name</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($accounts as $account): ?>
                    <tr>
                        <td>
                            <a href="/?q=account/profile&id=<?= $account->getId() ?>">
                                <?= htmlspecialchars($account->get('email')) ?>
                            </a>
                        </td>
                        <td>
                            <a href="/?q=account/profile&id=<?= $account->getId() ?>">
                                <?= htmlspecialchars($account->get('name')) ?>
                            </a>
                        </td>
                        <td></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        
    </div>
</div>