<?php
$error = $this->var('error');
?>
<style>
  .login-form {
    width: 500px;
    margin: 0 auto;
    padding: 20px;
    opacity: 0.9;
  }
</style>
<script type="text/javascript">
  var onloadCallback = function() {
    grecaptcha.render('recaptcha', {
      'sitekey': '6LcNGy8rAAAAAOKK-vDcqv0bBu6DdWtbtxSQP46N'
    });
  };
</script>
<script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit" async defer></script>

<div class="card login-form">
  <div class="right">
    <a href="/?q=auth/signup">Don't have an account?</a><br>
  </div>
  <h2>Welcome</h2>
  <form method="post">

    <?php if ($error): ?><p style="color:red"><?= htmlspecialchars($error) ?></p><?php endif; ?>

    <div class="fld">
      <input type="email" name="email" placeholder=" " required>
      <label>Email</label>
    </div>
    <div class="fld">
      <input type="password" name="password" placeholder=" " required>
      <label>Password</label>
    </div>

    <div class="button-set" style="display: flex; justify-content: space-between; align-items: center;">
      <a class="right" href="/?q=auth/forgot">Forgot password?</a>
      <button class="btn" type="submit">Login</button>
    </div>
    <div id="recaptcha" class="g-recaptcha" data-sitekey="your_site_key"></div>
    

  </form>
</div>