<?php
  $error = $this->var('error');
?>
<style>
  .login-form {
    width: 500px;
    margin: 0 auto;
    padding: 20px;
    opacity: 0.9;
  }
</style>

<div class="card login-form">
  <div class="right">
    <a href="/?q=auth/signup">Don't have an account?</a><br>
  </div>
  <h2>Wellcome</h2>
  <form method="post">
    
<?php if ($error): ?><p style="color:red"><?= htmlspecialchars($error) ?></p><?php endif; ?>      
      
    <div class="fld">
      <input type="email" name="email" placeholder=" " required>
      <label>Email</label>
    </div>
    <div class="fld">
      <input type="password" name="password" placeholder=" " required>
      <label>Password</label>
    </div>

    <div class="button-set" >
      <button class="btn" type="submit">Login</button>
      <a class="right" href="/?q=auth/forgot">Forgot password?</a>
    </div>
  </form>
</div>